import type { Metadata } from 'next';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Health Pathways',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <div className="flex h-screen">
          {/* <!-- Sidebar --> */}
          <div className="bg-white-800 absolute inset-y-0 left-0 w-64 -translate-x-full transform space-y-6 border-r-2 px-2 py-7 text-black transition duration-200 ease-in-out md:relative md:translate-x-0">
            {/* <!-- Logo or Brand --> */}
            <Link href="/" className="flex items-center space-x-2 px-4">
              <Image src="/images/CommunityTocLogo.svg" alt="HealthPathways logo" width="120" height="40" />
            </Link>
            {/* <!-- Navigation --> */}
            <nav>
              <a
                href="#"
                className="block rounded px-4 py-2.5 transition duration-200 hover:bg-gray-700 hover:text-white"
              >
                Navigation goes here
              </a>
            </nav>
          </div>

          {/* <!-- Main Content --> */}
          <div className="flex-1 p-4">
            <main>
              <div className="mx-auto max-w-7xl py-2 sm:px-6 lg:px-8">
                {/* <!-- Replace with your content --> */}
                {/* <div className="px-4 py-0 sm:px-0"> */}
                <div className="h-96 rounded-lg">{children}</div>
                {/* </div> */}
                {/* <!-- /End replace --> */}
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
